services:
  db:
    image: postgres:16-alpine
    container_name: torqueos-db
    environment:
      POSTGRES_DB: torqueos
      POSTGRES_USER: torqueos
      POSTGRES_PASSWORD: torqueos123
    ports:
      - "5432:5432"
    volumes:
      - torqueos_pgdata:/home/horacio/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U torqueos -d torqueos"]
      interval: 5s
      timeout: 3s
      retries: 30

 # app:
 #   build: .
 #   container_name: torqueos-app
 #   depends_on:
 #     db:
 #       condition: service_healthy
 #   environment:
 #     SPRING_PROFILES_ACTIVE: docker
 #   ports:
 #     - "8080:8080"

volumes:
  torqueos_pgdata:
